# Generated by Django 3.0.3 on 2020-03-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Enter department name', max_length=250, unique=True, verbose_name='Department name'),
        ),
    ]
