# Generated by Django 3.0.3 on 2020-03-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200302_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['first_name', '-updated_at'], 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name', '-updated_at']},
        ),
    ]
