# Generated by Django 3.0.3 on 2020-03-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200303_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bio',
            field=models.TextField(blank=True, help_text='Enter employee bio', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(help_text='Enter email', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(help_text='Enter first name', max_length=25),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(help_text='Enter last name', max_length=25),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(help_text='Enter midels name', max_length=25),
        ),
    ]
