# Generated by Django 3.0.3 on 2020-03-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200303_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name', '-updated_at'], 'permissions': (('can_create_department', 'Can create department'), ('can_edit_department', 'Can edit department'), ('can_delete_department', 'Can delete department'))},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['first_name', '-updated_at'], 'permissions': (('can_create_employee', 'Can create employee'), ('can_edit_employee', 'Can edit employee'), ('can_delete_employee', 'Can delete employee')), 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name', '-updated_at'], 'permissions': (('can_create_position', 'Can create position'), ('can_edit_position', 'Can edit position'), ('can_delete_position', 'Can delete position'))},
        ),
    ]
